version: "3.7"

services:
  app:
    build:
      context: ./api
    ports:
      - "8000:8000"
    volumes:
      - ./api/app:/app
    command: sh -c "python manage.py wait_for_db && python manage.py migrate && python manage.py runserver 0.0.0.0:8000" 
    depends_on:
      - db
  db:
    image: postgres:10-alpine
  fe:
    build:
      context: ./fe
    ports:
      - "8080:8080"
    volumes:
      - ./fe:/fe
    command: sh -c "npm run serve"
