version: "3.7"

    services:
      app:
        build:
          context: ./api
        ports:
          - "8000:8000"
        volumes:
          - ./api/app:/app
          command: sh -c "python manage.py wait_for_db && python manage.py migrate && gunicorn app.wsgi:application --bind 0.0.0.0:8000"
        env_file:
          - ./.env.prod 
        depends_on:
          - db
      db:
        image: postgres:10-alpine
        env_file:
          - ./.env.prod.db
      fe:
        build:
          context: ./fe
        ports:
          - "8080:8080"
        volumes:
          - ./fe:/fe
        command: sh -c "npm run serve"